baseURL = "https://wootcatchurch.com"
languageCode = "en-us"
title = "WootCat Church"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "WootCat"
    name = "AOTW"
    title = "AsOpposedToWhat"
    url = "https://asopposedtowhat.com/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact"
    weight = 0
